#Finding sum of all the prime numbers
import sys
print("Assigntment 2 - Part 2: Find the sum of all the primes below what the user inputs.")
print("")

primes = []

def isPrime(num):
    for i in range(2,int(num**0.5) + 1):
      if num%i == 0:
        return False
    return True

#Second function needed: get_primes yields an in nite sequence of prime numbers starting at the given argument value.
def getPrime(num):
  bel_num = int(input('Enter a number for the sum of prime to go below: '))
  print('You entered: ', bel_num)
  for i in(range(num, bel_num+1)):
    if isPrime(i) == True:
      primes.append(i)
  print("The sum of all primes below", bel_num, "=")

#Third function need: sum_primes iterates over the values generated by get_primes
#sums each value if it is prime, and breaks when the generated prime is greater than 2 million
def sumPrimes(num):
  if (isPrime(num) == True):
    getPrime(num)
    sumPrime=0
    for i in primes:
      sumPrime += i
    print (sumPrime)

sumPrimes(2)
